import { Metadata } from 'next';
import Script from 'next/script';
import Header from '@/components/layout/Header';
import AppWalletProvider from '@/provider/AppWalletProvider';
import { StateContextProvider } from '@/provider/StateProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Solana All In One',
  description: 'Generated by HighTech',
  applicationName: 'Solana All In One',
  generator: 'Next.js',
  authors: {
    name: 'HighTech',
  },
  keywords: [
    'solana',
    'token',
    'creation',
    'token 2022',
    'launch',
    'platform',
    'coin',
    'spl',
    'spl-token',
    'token extension',
    'solana all in one',
  ],
  icons: {
    icon: '/Sol-Logo.jpg',
  },
  openGraph: {
    type: 'website',
    // url: 'https://coinforge.fun',
    title: 'HighTech',
    description: 'Generated by HighTech',
    siteName: 'Solana All In One',
    images: [
      {
        url: 'https://i.ibb.co/yFDyJnVD/coinforge.jpg',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <title>HighTech</title>
        <meta name='description' content='Generated by HighTech' />
        <meta name='author' content='HighTech' />
        <meta
          name='keywords'
          content='Solana, Token, Creation, Token 2022, launch, platform, coin, spl, spl-token, token extension, solana all in one'
        />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link href='https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;700&display=swap' rel='stylesheet' />
        <Script async src='https://www.googletagmanager.com/gtag/js?id=G-15H4XSTRE5'></Script>
        <script
          id='google-analytics'
          dangerouslySetInnerHTML={{
            __html: `
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-15H4XSTRE5');
    `,
          }}
        />
      </head>
      <body className={`antialiased w-full bg-gradient-to-br from-gray-900 via-[#0c1527] to-main min-h-screen flex flex-col`}>
        <StateContextProvider>
          <AppWalletProvider>
            <Header />
            <main className='flex-1'>{children}</main>
          </AppWalletProvider>
        </StateContextProvider>
      </body>
    </html>
  );
}
